-- 코드를 입력하세요
SELECT C.CART_ID
  FROM CART_PRODUCTS C
  JOIN (
    SELECT CART_ID
      FROM CART_PRODUCTS
     WHERE NAME = 'Milk'
  ) AS T1
    ON C.CART_ID = T1.CART_ID
  JOIN (
    SELECT CART_ID
      FROM CART_PRODUCTS
     WHERE NAME = 'Yogurt'
  ) AS T2
    ON C.CART_ID = T2.CART_ID
  GROUP BY CART_ID
  ORDER BY ID
 