# -- 코드를 입력하세요
# SELECT P.PRODUCT_ID
#      , P.PRODUCT_NAME
#      , (SUM(AMOUNT) * PRICE) AS TOTAL_SALES
#   FROM FOOD_PRODUCT P
#   JOIN FOOD_ORDER O
#     ON P.PRODUCT_ID = O.PRODUCT_ID
#    AND O.PRODUCE_DATE LIKE '2022-05%'
#  ORDER BY TOTAL_SALES DESC, PRODUCT_ID 
 
 # SELECT SUM(AMOUNT) AS COUNT
 #   FROM FOOD_ORDER
 #  WHERE PRODUCE_DATE LIKE '2022-05%'
 #  GROUP BY PRODUCT_ID
  
SELECT P.PRODUCT_ID
     , P.PRODUCT_NAME
     , (P.PRICE * O.AMOUNT) AS TOTAL_SALES
  FROM FOOD_PRODUCT P
  JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
      FROM FOOD_ORDER
     WHERE PRODUCE_DATE LIKE '2022-05%'
     GROUP BY PRODUCT_ID
  ) AS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
 ORDER BY TOTAL_SALES DESC, PRODUCT_ID
    