-- 코드를 작성해주세요
SELECT YEAR(T1.DIFFERENTIATION_DATE) AS YEAR
     , (T2.YEAR_MAX - T1.SIZE_OF_COLONY) AS YEAR_DEV
     , T1.ID
  FROM ECOLI_DATA T1
 INNER JOIN(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
         , MAX(SIZE_OF_COLONY) AS YEAR_MAX
      FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)
  ) AS T2
    ON YEAR(T1.DIFFERENTIATION_DATE) = T2.YEAR
 ORDER BY YEAR, YEAR_DEV