-- 코드를 작성해주세요
SELECT H.SCORE
     , E.EMP_NO
     , E.EMP_NAME
     , E.POSITION
     , E.EMAIL
  FROM HR_EMPLOYEES E
  JOIN HR_DEPARTMENT D
    ON E.DEPT_ID = D.DEPT_ID
  JOIN (SELECT EMP_NO
         , SUM(SCORE) AS SCORE
      FROM HR_GRADE
     WHERE YEAR = 2022
     GROUP BY EMP_NO
     ORDER BY SUM(SCORE) DESC
     LIMIT 1) AS H
    ON H.EMP_NO = E.EMP_NO

 