-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR
     , MONTH(S.SALES_DATE) AS MONTH
     , COUNT(DISTINCT I.USER_ID) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT I.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
  FROM ONLINE_SALE S
  JOIN (SELECT USER_ID, JOINED
          FROM USER_INFO
         WHERE YEAR(JOINED) = 2021
        ) AS I
    ON S.USER_ID = I.USER_ID
 GROUP BY YEAR, MONTH
 ORDER BY YEAR, MONTH