-- 코드를 입력하세요


SELECT U.USER_ID
     , U.NICKNAME
     , T.TOTAL_SALES
  FROM USED_GOODS_USER U
  JOIN (
    SELECT WRITER_ID
         , SUM(PRICE) AS TOTAL_SALES
      FROM USED_GOODS_BOARD
     WHERE STATUS = 'DONE'
     GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
  ) AS T
    ON T.WRITER_ID = U.USER_ID
 ORDER BY T.TOTAL_SALES