SELECT HISTORY_ID
     , ROUND(DAILY_FEE * DURATION * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100) AS FEE
  FROM (
        SELECT H.HISTORY_ID
             , C.DAILY_FEE
             , C.CAR_TYPE
             , DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION,
               CASE 
                    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
                    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
                    WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
                    ELSE NULL
                END AS DURATION_TYPE
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          JOIN CAR_RENTAL_COMPANY_CAR C
            ON H.CAR_ID = C.CAR_ID
         WHERE C.CAR_TYPE IN ('트럭')
        ) AS T
   LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
     ON T.CAR_TYPE = P.CAR_TYPE
    AND T.DURATION_TYPE = P.DURATION_TYPE
  ORDER BY FEE DESC, HISTORY_ID DESC