SELECT DISTINCT D.ID AS ID
     , D.EMAIL AS EMAIL
     , D.FIRST_NAME AS FIRST_NAME
     , D.LAST_NAME AS LAST_NAME
  FROM DEVELOPERS D
  JOIN SKILLCODES S
    ON (D.SKILL_CODE & S.CODE) 
 WHERE S.NAME IN ('Python', 'C#')
 ORDER BY D.ID